### ISSUE TITLE
Error: missing field `cache`

### ISSUE THREAD

**Issue by adorton-adobe** [adobe/frl-online-proxy#6]
**Description**

When starting the proxy in `cache`, `store`, or `forward` mode with no config, the application reports this error:

```
Error: missing field `cache`
```

**Steps to reproduce**

Run the proxy with no config and a non-passthrough mode.

```
>  .\frl-proxy.exe start -m c
Error: missing field `cache`
```

**Expected behavior**

If we implement the feature suggested in #5, the proxy application should report an error to the effect of `cache db path must be specified for this mode`.

**Environment**
 - frl-proxy version: unstable
 - OS type and version: Windows 10

**Comment by adorton-adobe** [comment]
We also get this error when running `start` with no parameters or explicitly in `passthrough` mode.

**Comment by adorton-adobe** [comment]
The solution is to add a bare `[cache]` object to `res/defaults.toml`

```toml
[proxy]
mode = "passthrough"
host = "127.0.0.1:3030"
remote_host = "https://lcs-cops.adobe.io"
ssl = false

[logging]
console_log_level = "info"
log_to_file = false
file_log_level = "info"
file_log_path = "frl-proxy.log"

[cache]
```

Fixing this lets us run in `passthrough` mode with no config and also reports the correct error when attempting a different mode with no cache file specified.

```
.\frl-proxy.exe start -m c
Error: cache_file_path must be specified if the cache is enabled

Location:
    src\settings.rs:118:24
```
